Update CICD with OIDC config
NASA-IMPACT/veda-config-ghg pull request #11
Opened 2023-06-28 20:37 UTC by slesaad

## What am I changing and why

- Update CI/CD to use OIDC to connect to Github (better than long-lived keys, same pattern in other GHGC stacks)
- Get rid of subpath for deployment (the dashboard will not be deployed to a subpath)
- Remove Github token (since the repos are already public)
- Set environment based on branch and deploy

## How to test
- I've tested it with the MCP staging environment (frontend accessible yet, I've made a bucket policy change request in MCP)
- Should automatically deploy to staging (future url: staging.ghg.center) on merge to develop

2023-07-05 10:23 UTC, danielfdsilva requested changes

2023-07-05 10:23 UTC, danielfdsilva commented on .github/workflows/deploy.yml
> +          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }}
```suggestion
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }}  --delete
```
Should include the delete to clear out old files

2023-07-05 10:23 UTC, danielfdsilva commented on .github/workflows/deploy.yml
> +        run: PUBLIC_URL="${{ env.DOMAIN }}" yarn build
This would be an improvement, but it would be better to have the full domain, both for prod and staging. - not critical though

2023-07-06 15:43 UTC, slesaad commented on .github/workflows/deploy.yml
> +        run: PUBLIC_URL="${{ env.DOMAIN }}" yarn build
Updated to have individual domains.

staging: https://staging.ghg.center/
prod: https://ghg.center/

That's how to values should be, right?

2023-07-06 16:42 UTC, danielfdsilva commented on .github/workflows/deploy.yml
> +        run: PUBLIC_URL="${{ vars.DOMAIN }}" yarn build
this is very cool!

2023-07-06 17:39 UTC, merged