Add page disclaimers
NASA-IMPACT/veda-config-ghg pull request #136
Opened 2023-09-20 11:41 UTC by nerik

Adds the possibility to open a disclaimer modal upon entering a given section of the dashboard; currently Analysis and  Dataset Explore. Uses a localStorage item to prevent the disclaimers to show up again if the user don't want to (which is the default choice)

2023-09-20 13:21 UTC, hanbyul-here commented on overrides/components/page-footer/component.tsx
> +  explore: {
We can use the routes defined in https://github.com/NASA-IMPACT/veda-ui/blob/main/app/scripts/utils/routes.ts?

2023-09-20 13:25 UTC, hanbyul-here commented on overrides/components/page-footer/component.tsx
> +const MODALS_DISMISSED_KEY = "modalsDismissedKey";
prefix the key name since it is pretty generic?

2023-09-20 13:27 UTC, hanbyul-here reviewed
This seems a better approach than touching the ui code. I left two comments

2023-09-20 19:41 UTC, j08lue requested changes
It seems like the modal on Analysis won't show if I clicked the one on Exploration away, and vice versa.

If that is the case, we need to change that, please - the modals are different on each tool and the user needs to acknowledge them all at least once, please.

2023-09-21 09:48 UTC, nerik commented
@j08lue Good catch. There was an issue when switching from one page to another. Should be fixed now.

2023-09-21 14:49 UTC, hanbyul-here approved these changes
Ah I didn't notice that we don't have explore path exported from ui module. it looks good to me.

2023-09-21 18:46 UTC, merged