updated the default metrics for the datasets
NASA-IMPACT/veda-config-ghg pull request #229
Opened 2023-11-20 21:32 UTC by SwordSaintLancelot

## Why are you creating this Pull Request?
The default metric has been added to all the layers of every dataset for the US GHG center.

2023-11-20 22:11 UTC, j08lue requested changes
@SwordSaintLancelot there seem to be indentation errors that caused the preview build to fail. See the CI job logs for details, please.

2023-11-20 22:17 UTC, SwordSaintLancelot commented
@j08lue I did look into the logs and it mentioned that the issue is with duplicate mapping key. I checked the indentation and it seems to be correct (at least similar to the example that you did)

2023-11-20 23:08 UTC, slesaad commented on datasets/noaa-cpfp-co2-point.data.mdx
> +    analysis:
can you add back `exclude: true` in the analysis?

2023-11-20 23:09 UTC, slesaad commented on datasets/emit-ch4plume-v1.data.mdx
> +      metrics:
can you add back `exclude: true` here

2023-11-20 23:10 UTC, slesaad commented on datasets/emit-ch4plume-v1.data.mdx
> +      metrics:
same for all the epa layers

2023-11-20 23:11 UTC, slesaad requested changes
Also don't push .veda/ui changes?

2023-11-21 16:27 UTC, slesaad commented
@SwordSaintLancelot don't add exclude to all the datasets, only to those that already had it

2023-11-21 17:14 UTC, SwordSaintLancelot commented
> Also don't push .veda/ui changes?

Reverted them to their original state.

2023-11-21 20:42 UTC, slesaad commented on package.json
> +  "version": "0.1.0",
🤔

2023-11-21 20:51 UTC, j08lue commented on package.json
> +  "version": "0.1.0",
Looks like this branch here should be rebased to current `develop` or something? Where you did you branch off from, @SwordSaintLancelot?

2023-11-21 21:16 UTC, SwordSaintLancelot commented on package.json
> +  "version": "0.1.0",
I did branch it from develop. I will rebase it and push again.

2023-11-21 21:18 UTC, j08lue commented on package.json
> +  "version": "0.1.0",
Thanks. I was just worried about the "reverting" commits above. If these changes are already in `develop` by now _and mean to be there_, your commits here would undo them.

2023-11-21 21:23 UTC, SwordSaintLancelot commented on package.json
> +  "version": "0.1.0",
I think there were a few changes that happened when I ran the yarn serve and that's what modified the /.veda/ui folder along with package.json but I changed those to original package.json which was in the develop branch.

2023-11-22 15:22 UTC, slesaad approved these changes

2023-11-22 16:47 UTC, merged