Feature: google analytics
NASA-IMPACT/veda-config-ghg pull request #26
Opened 2023-07-27 22:15 UTC by slesaad

## What am I changing and why

Add google analytics id

TODO:
- create tag manager container (delegated)
- updated github environment secrets

2023-08-02 11:05 UTC, danielfdsilva approved these changes

2023-08-02 14:30 UTC, hanbyul-here approved these changes
I can't check environment variables on this repo, but I trust you! 
+ but this pr itself doesn't seem to be necessary. see my comment.

2023-08-02 17:00 UTC, danielfdsilva commented on .env
> +GOOGLE_ANALYTICS_ID='G-738TR1H3KE'
You're totally right @hanbyul-here . I completely missed this.
We did set up Google Tag Manager, but never configured it.

@slesaad The needed env vars actually are:
```
GOOGLE_TAG_MANAGER_ID=''
GOOGLE_TAG_AUTH=''
GOOGLE_TAG_PREVIEW=''
```

2023-08-02 17:01 UTC, danielfdsilva requested changes
Se comment above

2023-08-02 17:59 UTC, hanbyul-here commented on .env
> +GOOGLE_ANALYTICS_ID='G-738TR1H3KE'
We moved this to env.local (https://github.com/NASA-IMPACT/veda-config/blob/develop/.env.local-sample) We just need to clean up google analytics id.

2023-08-02 18:48 UTC, slesaad commented on .env
> +GOOGLE_ANALYTICS_ID='G-738TR1H3KE'
I did update the Google Tag Manager env vars, they're in the repository secrets. I saw the env var and also read that GTM and GA are to be used together, so thought we needed both.

So it's safe to close this PR? maybe I could remove the entry from the .env file itself.

2023-08-03 09:29 UTC, danielfdsilva commented on .env
> +GOOGLE_ANALYTICS_ID='G-738TR1H3KE'
that's a great idea @slesaad

2023-08-07 15:11 UTC, merged